version = "2.9.*"
requires = ["types-pyasn1"]

[tool.stubtest]
apt_dependencies = ["libkrb5-dev"]
# No need to install on the CI. Leaving here as information for MacOs/Windows contributors.
# brew_dependencies = ["krb5"]
# choco_dependencies = ["mitkerberos"]
