version = "7.45.2"

[tool.stubtest]
ignore_missing_stub = false
# Install on Windows requires building PycURL from source
#
# Install on MacOS is too complicated for the CI and does not work with stubtest:
# % brew install openssl
# % export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
# % export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
# % pip install --compile --install-option="--with-openssl" pycurl
# TODO: Test on Windows and/or MacOS once wheels are available.
platforms = ["linux"]
apt_dependencies = ["libcurl4-openssl-dev"]
# No need to install on the CI. Leaving here as information for MacOS contributors.
# brew_dependencies = ["openssl"]
